### ISSUE TITLE
track deletes of trees

### ISSUE THREAD

**Issue by quite** [fruktkartan/fruktkartan-api#14]
Deleting a tree doesn't leave any trace, hashed ip, of who dunnit. Should we arrange for something, somehow... Or we wait and see what happens, we have the history :)

**Comment by quite** [comment]
Require a comment on why the tree is deleted? And would log the hashed ip along with that, all in a separate table. Perhaps that's just too much...

**Comment by rotsee** [comment]
I think asking for a comment is a good idea. It introduces just the right amount of “friction”. +1

**Comment by quite** [comment]
I've been seeing quite a few vandalism deletes during the past few weeks (I look a our fruktsam history web page once in a while). One type are trees that I know or can verify still are there. And also some very suspicious patterns of deletion, like deletion within the minute of 5 trees standing next to each other. I have undeleted a couple of handful of trees, and that's a tedious job.

I'd vote for disabling deletion of trees until we have a way for user to write a reason for deletion (and perhaps also a flow for undeletion). What do you think @rotsee

**Comment by rotsee** [comment]
Sounds reasonable. Let's disable deletion for now
