### ISSUE TITLE
update legacy ssm_keys

### ISSUE THREAD

**Issue by quite** [fruktkartan/fruktkartan-api#15]
Here are sql update statements to fixup the legacy ssm_key. I think they are sound, go ahead and run them if you think the same @rotsee  :)

https://gist.github.com/quite/e6d805a2673c1df0343e58e1813038d8

**Comment by rotsee** [comment]
fixed!
(This also means that the primary key column, `ssm_key`, no longer needs to be 64 characters wide.)
