### ISSUE TITLE
postgis for heroku free plan

### ISSUE THREAD

**Issue by quite** [fruktkartan/fruktkartan-api#2]
Does this indicate that postgis is available for the free plan? https://elements.heroku.com/addons/heroku-postgresql

https://github.com/fruktkartan/fruktkartan-api/blob/f03adafd878cea6e4edc0c1303bd35595613e3f2/routes/v1/trees.js#L32

**Comment by quite** [comment]
Looking at the dashboard, we seem to be using a postgres at aws though, right?

**Comment by rotsee** [comment]
Yup, Heroku is all built on AWS, including the official “add-ons”

**Comment by quite** [comment]
Aha! That's the setup.

**Comment by quite** [comment]
I did `CREATE EXTENSION postgis` in the database, and then adapted the queries, testing them out on a copy of the trees table. Seems to work, but the code is completely untested...
I think we need a second opinion and some real testing :-)

Here is what needs to be done to the trees table:
```
ALTER TABLE trees ADD COLUMN point GEOMETRY(point);
UPDATE trees SET points = ST_MakePoint(lon, lat);
ALTER TABLE trees DROP COLUMN lat;
ALTER TABLE trees DROP COLUMN lon;
```
