### ISSUE TITLE
flag reason is empty

### ISSUE THREAD

**Issue by quite** [fruktkartan/fruktkartan-api#29]
I suspect this should be `req.params.reason`?

https://github.com/fruktkartan/fruktkartan-api/blob/dad95931337f75ad4cb44cdf9b6c8315253be053/routes/v1/flag.js#L20

**Comment by quite** [comment]
Nah, maybe req.body.reason?

**Comment by rotsee** [comment]
query or body, either would have worked if I only had remembered to actually send the data from the frontend.... :)

Any way, probably better to use the request body here, to avoid having to deal with uri encoding, so I'm changing taht too
