### ISSUE TITLE
maximum 10000 rows in heroku postgres hobby-dev/free tier

### ISSUE THREAD

**Issue by quite** [fruktkartan/fruktkartan-api#4]
We need to be aware :o

**Comment by rotsee** [comment]
Good catch. I'll upgrade to a paid plan then. Still much cheaper than the current solution

**Comment by quite** [comment]
Oh I thought it was completely free currently?

**Comment by rotsee** [comment]
Yes, I meant compared to Fruktkartan 1.0 :)

**Comment by quite** [comment]
Ah, :D   ... btw I did `ALTER TABLE trees ALTER COLUMN point SET NOT NULL` in the live db ... And updated the README. Also removed `lat` and `lon` from there, but did *not* remove them from live db. Don't know if you maintain the schema elsewhere.

**Comment by quite** [comment]
I'm *slowly* working on something that eats the `history` table, and builds some kind of visualization of what has happened. Removed, added trees. Maybe moved trees, alterered type, descriptions. Don't know at all how to present it.

Perhaps this could actually consume the history entries it processes, removing them from the table!

**Comment by quite** [comment]
I removed some thousands of bulk edits from May.

And finally got a brutalist, information-dense thing deployed https://fruktkartan.se/historik/  (automatically from https://github.com/fruktkartan/fruktsam). It doesn't consume the entries for now.

**Comment by quite** [comment]
Hm, I guess we moved to a paid plan, and could close this?

**Comment by rotsee** [comment]
Indeed
